/**
 * Generate a self-contained inline Dockerfile for `agentio mcp teleport`.
 *
 * siteio's "inline Dockerfile" mode builds containers in an empty build
 * context — the Dockerfile cannot `COPY` or `ADD` anything from the
 * local filesystem. Everything the container needs has to be fetched at
 * build time via `RUN curl`.
 *
 * This generator produces a Dockerfile that:
 *   1. Installs ca-certificates, curl, and tini (for signal handling).
 *   2. Creates a non-root `agentio` user with /data as HOME.
 *   3. Fetches the release binary for the target platform at BUILD time,
 *      so siteio/Docker can cache the layer and re-deploys are fast.
 *   4. Runs `agentio config import` at container START, reading the
 *      encrypted blob from the `AGENTIO_KEY` + `AGENTIO_CONFIG` env
 *      vars (set by siteio via `apps set -e`).
 *   5. Starts the HTTP server on port 9999, bound to 0.0.0.0.
 *
 * The generator is a pure function — no I/O, no side effects — so it's
 * trivially unit-testable. Tests in dockerfile-gen.test.ts pin down the
 * exact structure (HEALTHCHECK, EXPOSE, user, entrypoint, etc) so a
 * well-meaning refactor can't silently break the container image.
 */

export interface TeleportDockerfileOptions {
  /** GitHub release version tag to pin, without the leading "v". Omit to always fetch "latest". */
  version?: string;
  /** Port the server should bind inside the container. Defaults to 9999. */
  port?: number;
}

const DEFAULT_PORT = 9999;

export function generateTeleportDockerfile(
  opts: TeleportDockerfileOptions = {}
): string {
  const port = opts.port ?? DEFAULT_PORT;
  // Inject a fixed version into the RUN block if the caller pinned one;
  // otherwise fall through to the GitHub "latest" redirect.
  const versionResolver = opts.version
    ? `VERSION="${opts.version}"`
    : `VERSION=$(curl -sL https://api.github.com/repos/plosson/agentio/releases/latest | grep '"tag_name"' | sed -E 's/.*"v([^"]+)".*/\\1/')`;

  return `# Auto-generated by \`agentio mcp teleport\`. Do not hand-edit.
# This is a self-contained "inline Dockerfile" for siteio — it must not
# reference any files from a local build context. Everything is fetched
# at build time via curl.

FROM ubuntu:24.04

# Runtime dependencies:
#   ca-certificates : HTTPS calls from the container
#   curl            : release binary download + healthcheck
#   tini            : proper PID 1 / signal handling
#   gosu            : drop privileges from root to the agentio user at
#                     container START (AFTER we've chowned the persistent
#                     /data volume, which Docker mounts as root-owned)
RUN apt-get update && apt-get install -y --no-install-recommends \\
    ca-certificates curl tini gosu \\
    && rm -rf /var/lib/apt/lists/*

# Non-root user. /data will be a siteio-managed persistent volume mount,
# so its build-time ownership is meaningless — the volume masks whatever
# we chown here at image-build time. We fix ownership at container-START
# via the entrypoint script below (requires root, hence no USER directive).
RUN groupadd -g 1001 agentio \\
    && useradd -u 1001 -g agentio -d /home/agentio -m agentio \\
    && mkdir -p /data /home/agentio/bin \\
    && chown -R agentio:agentio /home/agentio/bin

# Fetch the agentio linux binary at BUILD time (not boot) so siteio
# caches the layer and subsequent deploys reuse it unless --no-cache
# is passed. Architecture is detected at build time.
RUN set -eux; \\
    ARCH=$(uname -m); \\
    case "$ARCH" in \\
        aarch64|arm64) PLATFORM="linux-arm64" ;; \\
        x86_64|amd64)  PLATFORM="linux-x64" ;; \\
        *) echo "unsupported arch: $ARCH" >&2; exit 1 ;; \\
    esac; \\
    ${versionResolver}; \\
    echo "Installing agentio v\${VERSION} (\${PLATFORM})..."; \\
    curl -fL "https://github.com/plosson/agentio/releases/download/v\${VERSION}/agentio-\${PLATFORM}" \\
        -o /home/agentio/bin/agentio; \\
    chmod +x /home/agentio/bin/agentio; \\
    chown agentio:agentio /home/agentio/bin/agentio

ENV HOME=/data
ENV XDG_CONFIG_HOME=/data
ENV PATH="/home/agentio/bin:\${PATH}"

EXPOSE ${port}

# Healthcheck hits the agentio /health endpoint. start-period is 30s
# because importing the config on first boot involves decrypting the
# AGENTIO_CONFIG blob which can take a couple seconds on slow hardware.
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \\
    CMD curl -sf http://localhost:${port}/health || exit 1

# tini becomes PID 1 for signal handling. The sh -c script runs as ROOT
# so it can chown the freshly-mounted /data volume (Docker mounts named
# volumes with root:root ownership on first boot, overriding any
# build-time chown), then drops to the agentio user via gosu and exec's
# the config-import + server pipeline so SIGTERM propagates correctly.
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["sh", "-c", "chown -R agentio:agentio /data && exec gosu agentio sh -c 'agentio config import && exec agentio server start --foreground --host 0.0.0.0 --port ${port}'"]
`;
}
